### ISSUE TITLE
Use the Statamic fallback controller

### ISSUE THREAD

**Issue by indykoning** [rapidez/statamic#27]
Currently the fallback controller is linked to our own rewrite controller only gathering pages. Which means other collections and routes will have to be added manually.

I see that Statamic works mostly using it's fallback controller which gets disabled when routes are disabled.
https://github.com/statamic/cms/blob/3.4/routes/web.php#L51
Maybe we can simply register this [FrontendController](https://github.com/statamic/cms/blob/b5aeb0f0f57f5ecd0b62d11395eb5f81ea4bcc15/src/Http/Controllers/FrontendController.php#L28) in our fallback routing so any route natively functional in Statamic is functional in Rapidez

**Comment by royduin** [comment]
Fixed in v1
