### ISSUE TITLE
Conditional fields support

### ISSUE THREAD

**Issue by royduin** [rapidez/statamic#31]
If we need a conditional field somewhere we need to create a custom JS driver to make this possible: https://statamic.dev/tags/form-create#custom-js-drivers

**Comment by BobWez98** [comment]
@royduin If this needs to be a Vue driver it already exists(and also mentioned in the docs) https://gist.github.com/jesseleite/3507f7ad3dd062b9e5f7592c899bf297 .

**Comment by royduin** [comment]
https://github.com/rapidez/statamic/pull/34 🚀
